### ISSUE TITLE
Heading link number not visible in Windows high contrast mode

### ISSUE THREAD

**Issue by ayesha-77** [stringyland/bookmarklets#3]
**Issue description**
* The heading link number is not visible in Windows high contrast mode. This is because it is a CSS ::before element.

**Severity**
High

**Occurs on**
* Windows 11/Edge 116.0.19/Windows High Contrast Mode

How to replicate:
1. Navigate to https://stringyland.github.io/bookmarklets/headings-skipped.html on Edge and use the bookmarklet
2. Turn on Windows high contrast mode. 
3. Notice how the heading link numbers are not visible.

**Expected behaviour**
* No loss of content should occur when Windows high contrast mode is on.

**Actual behaviour**
* Ensure the heading link numbers are visible in Windows High Contrast Mode. Use HTML instead to display the number, rather than CSS. 

<img width="924" alt="2023-09-08_15-40-59" src="https://github.com/stringyland/bookmarklets/assets/144410097/7e4c0139-b3d8-4d32-bb1b-680adf725621">

**Comment by stringyland** [comment]
Updated with a fix. 
- edited script to put level number in the HTML instead of using CSS content property
- edited CSS to use CanvasText and Canvas as system-color keywords

Interestingly, the keywords didn't work until I used CanvasText with Canvas. I think the background and foreground keywords need to match, e.g. ButtonText with ButtonFace.
